### ISSUE TITLE
Corrupted download image 

### ISSUE THREAD

**Issue by HemaZ** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#10]
hello, 
in the beginning, I really want to thank you for this great tool. it saved me a lot of time and effort 

i got a problem when i press the download button after I segmented an image.

it is shown in this screenshot 

![image](https://user-images.githubusercontent.com/6087928/43986492-ccce0b70-9d11-11e8-8c07-7f0012b42da2.png)

![image](https://user-images.githubusercontent.com/6087928/43986526-6d6e2830-9d12-11e8-9bad-4d2030470f54.png)

**Comment by dmandrioli** [comment]
Hey, are you using Firefox? If yes, your issue can be related to #2, you may want to try with Chrome/Chromium to see if the problem occurs.

**Comment by HemaZ** [comment]
@dmandrioli I tried chrome and the same happens. except the .json file output is okay but the output image is corrupted

**Comment by HemaZ** [comment]
@dmandrioli  i tried several images and the same is happening. 
I'm running the editor using meteor on Ubuntu 18.04
