### ISSUE TITLE
Move through the scene with keyboard arrow keys

### ISSUE THREAD

**Issue by DarioSiroki** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#100]
Would you accept if I made a pull request to move through the scene with WASD? I'm talking about X and Z axis. It's a simple addition which only requires some configuration of [OrbitControls](https://threejs.org/docs/#examples/en/controls/OrbitControls).

And a question for you, do you have any idea what would be the easiest way to add Q/E keys to change height (Y axis)? I'm not too experienced with Three.js (not at all actually), but it looks like switching to any other controlling model would be too complex or just make things worse. My conclusion is that the best option would be to edit the OrbitControls to make this possible?

**Comment by dmandrioli** [comment]
Hi, you are free to submit pull requests and you are right, improving navigation can't be achieved by modifying OrbitControls.

**Comment by DarioSiroki** [comment]
Thanks, I will make a pull request for height navigation too maybe if I will need it or if I will have time

**Comment by dmandrioli** [comment]
Fixed in 1.5.2
