### ISSUE TITLE
 Cannot label about 400MB PCD point cloud file

### ISSUE THREAD

**Issue by jiang-li1** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#105]
I want to use this software to mark the scene point cloud I collected, about 400MB of scene point cloud similar to semantic3D, but the browser will not load after opening it. Is it the problem of insufficient initial memory settings? What should i do

**Comment by dmandrioli** [comment]
Hi, can you share a 400MB pointcloud to see what could be done?
