### ISSUE TITLE
can not load 128line pcd file

### ISSUE THREAD

**Issue by fuqiangZ** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#106]
My point cloud data file is 128line. Size is  6M. 
I can not load it to the system, as it show me  "Loading Object"

Besides, I can open it with this editor: https://github.com/halostorm/PCAT_open_source

Below is the pcd file.
[1824.836257930.pcd.zip](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/files/5107453/1824.836257930.pcd.zip)

**Comment by dmandrioli** [comment]
Your PCD file has to conform to this format https://pointclouds.org/documentation/tutorials/pcd_file_format.html
I guess the format used by PCAT_open_source is not standard.
