### ISSUE TITLE
Error: METEOR_SETTINGS are not a valid JSON

### ISSUE THREAD

**Issue by davodogster** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#108]
Here is the command I run and the error I get ( I also tried docker compose but it didn't work on localhost)
![image](https://user-images.githubusercontent.com/46079516/91931150-bfcb2580-ed36-11ea-8e68-2beb0e60bb6c.png)

Here is my Settings.JSON file:

![image](https://user-images.githubusercontent.com/46079516/91931199-df624e00-ed36-11ea-9c88-aa4715b79df9.png)

Can anyone help me please?

**Comment by dmandrioli** [comment]
Maybe you have to remove the double quotes around $(cat...) ?
