### ISSUE TITLE
Only up to 20 images appearing

### ISSUE THREAD

**Issue by sotoy** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#113]
For some reason I link the json to a folder with over 600 images, and I can only opt for the first 20 of them. Am I doing something wrong?

**Comment by dmandrioli** [comment]
I'm aware of it (#110) but no time to work on the project for now. Thanks for reporting.

**Comment by dmandrioli** [comment]
You can find a cheap workaround here: https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/issues/109#issuecomment-718269848
