### ISSUE TITLE
Error on meteor npm start

### ISSUE THREAD

**Issue by Soumya-V-S** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#118]
Hi,
  I got on error on running the meteor npm start command. Error is given below.

Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with static-html (for target web.browser):
   Semantic Segmentation Editor.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.

Please help me in solving the issue.

**Comment by dmandrioli** [comment]
Hi, it works on my side, you may try again from a freshly cloned repository.

```
git clone ...
cd semantic-segmentation-editor
meteor npm install
meteor npm start
```
