### ISSUE TITLE
Empty file from PCD output

### ISSUE THREAD

**Issue by DKandrew** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#12]
I am looking for an segmentation tool which will filter only the point cloud that I am interested in. Take the [demo point cloud sever](http://sse.hup.li/edit/%2Fsamples%2Fpointcloud.pcd) as an example. I have segmented out the car manually. But when I click the "PCD output", I get a PCD file with 0kb size. Is this a bug, could I output a PCD file with only the point cloud I am interested in?

**Comment by dmandrioli** [comment]
The tool takes a single PCD as input and produces a labeled PCD file, there is no way to label multiple point clouds at the same time.

For your particular use-case of labeling several frames of a stationary Lidar, having a selection polygon that would apply to several point clouds would fit your need but it's not implemented.
For now the way to go is to merge point clouds with an external tool before labeling the merged point clouds.

The number of points you can manipulate mainly depends on your graphic card capabilities.
