### ISSUE TITLE
Intensity value in Viewing and Exported .pcd

### ISSUE THREAD

**Issue by Benjamin-Tan** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#121]
Thanks for such an amazing editor tool. Is it possible to have the above-mentioned feature to be merged into the main release? I have seen an attempt in #53 but it has been closed but not merged to the main release.

**Comment by dmandrioli** [comment]
Thank you :)
The mentioned PR has not been merged but a support for Intensity display has been implemented in 1.4.0 (https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/compare/1.3.0...1.4.0)
Hope this helps.

**Comment by dmandrioli** [comment]
Hum sorry in fact this is about RGB not intensity.

**Comment by dmandrioli** [comment]
I remember the story now. Supporting RGB point clouds lets you encode intensity as RGB. So it's up to you to provide RGB values to represent intensity. Thanks.

**Comment by Benjamin-Tan** [comment]
thanks for the speedy reply. So you would recommend to use RGB to represent the intensity value instead of having XYZIRGB?

**Comment by dmandrioli** [comment]
Yes, this is what is supported by the tool.
