### ISSUE TITLE
setting.json

### ISSUE THREAD

**Issue by soccken** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#137]
I'm sorry, I accidentally erased the issues.
It's in setting.json.
{
  "configuration": {
    "images-folder": "/home/sematic-segmentation-editor",
    "internal-folder": "",
    "demo-mode": false
  },
  "sets-of-classes": [
    {
      "name": "Cityscapes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Road", "color": "#804080", "icon": "Road"},
      {"label": "Sidewalk", "color": "#F423E8", "icon": "NaturePeople"},
      {"label": "Parking", "color": "#FAAAA0", "icon": "Parking"}
    ]
    },
    {
      "name": "AD20",
      "objects": [
        {"label": "VOID", "color": "#CFCFCF"},
        {
          "label": "Void",
          "color": "#FF8800",
          "icon": "BorderNoneVariant"
        }, {
          "label": "Road",
          "color": "#799024",
          "icon": "Road"
        },
        {
          "label": "Pedestrian",
          "color": "#FAFFF5",
          "icon": "Walk"
        },
        {
          "label": "Car",
          "color": "#FF6D67",
          "icon": "Car"
        },
        {
          "label": "Truck",
          "color": "#FF5B8E",
          "icon": "Truck"
        },
        {
          "label": "Bus",
          "color": "#FF6FA2",
          "icon": "Bus"
        },
        {
          "label": "On rails",
          "color": "#FF7FC3",
          "icon": "Train"
        },
        {
          "label": "Motorcycle",
          "color": "#FFA859",
          "icon": "Motorbike"
        },
        {
          "label": "Bicycle",
          "color": "#FFDB62",
          "icon": "Bike"
        },
        {
          "label": "Sky",
          "color": "#87D8FF",
          "icon": "WeatherPartlycloudy"
        },
        {
          "label": "Vegetation",
          "color": "#7BC32B",
          "icon": "PineTree"
        },
        {
          "label": "Sidewalk",
          "color": "#827E67",
          "icon": "NaturePeople"
        },
        {
          "label": "Traffic sign",
          "color": "#9E9BFF",
          "icon": "SignDirection"
        },
        {
          "label": "Lane marking",
          "color": "#DDCDFF",
          "icon": "RoadVariant"
        },
        {
          "label": "Building",
          "color": "#785C6F",
          "icon": "HomeVariant"
        },
        {
          "label": "Traffic light",
          "color": "#119599",
          "icon": "SignDirection"
        },
        {
          "label": "Snow covered",
          "color": "#F1F1EF",
          "icon": "Snowflake"
        },
        {
          "label": "Pole",
          "color": "#FBB577",
          "icon": "Instapaper"
        },
        {
          "label": "Unpaved road",
          "color": "#C0AE89",
          "icon": "BlurLinear"
        },
        {
          "label": "Guard rail",
          "color": "#4D3D48",
          "icon": "SignCaution"
        }
      ]
    },
    {
      "name": "4 Classes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Class 1"},
      {"label": "Class 2"},
      {"label": "Class 3"},
    ]
    }
  ]
}

**Comment by dmandrioli** [comment]
The JSON syntax of your file is not valid.
You have a trailing comma after the definition of "Class 3''...
