### ISSUE TITLE
Where are the current 2D labels cached/stored?

### ISSUE THREAD

**Issue by mbcel** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#143]
I can see that for the 3D editor the labels are stored in sse-internal. However for the 2D editor it is not clear to me where the current labels are stored/cached? These are stored somewhere since I can see that on restart of the app previous generated labels are also restored.

Where can I find these cached results to be able to extract it and also delete it for a clean restart? Are these stored in meteor internally somewhere? I really could not find any folder relating to this...

**Comment by dmandrioli** [comment]
For bitmap labeling, data are stored in the Mongo database provided by Meteor.
