### ISSUE TITLE
Point Cloud Editor unable to load large size .pcd files

### ISSUE THREAD

**Issue by madhavkarri** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#145]
Able to successfully load 19 MB file into the point cloud editor and visulaize the point cloud. 
But the editor is not able to load 1GB .pcd file.  
Is there a limit on the file size?
Tested on both windows and Unix plaforms, behavior is similar.
Tested using both native and docker installations, behavior is similar.
RAM is not the limitation. Consumed only 25% of total RAM when trying to load 1Gb file. Total RAM is about 32 GB.
It shows that the file is being loaded by two rotating arrows, but the point cloud is not dispalyed even after 20-30 mins.

**Comment by dmandrioli** [comment]
Hello, there is no specific limitation on the file size. Performance mainly depends on your hardware and number of points in the .pcd.

Could you share a 1GB .pcd file to see what is the bottleneck?

**Comment by madhavkarri** [comment]
Hello Damien,
Thank you for responding so quickly. Trying to get some approavals to share the 1Gb file.
In the mean time, is there an option to spread out the processes to multiple cpu cluster that will help load the 1 Gb file.
On my local machine I was able to load the 400 MB file, but the mouse operations are not quite smooth and there is a significant lag.

**Comment by Jeehoon-K** [comment]
@madhavkarri 
Hi, I have the same problem with my pcd file. Did you fix your problem?

**Comment by hop-soellingeraj** [comment]
I have the same problem.  My file has 20M points in it.  Can this tool handle that?  Does the tool use the GPU by default, because I am not seeing any activity on `nvidia-smi` as it loads the pcd file

**Comment by madhavkarri** [comment]
From the tool author:
"It depends on your machine but I don't expect the tool to be able to load more than a few millions of points. I did some tests hacking the source code. On my Mac Mini of 2018, navigating the point cloud starts to be painful at about 5M of points"

**Comment by madhavkarri** [comment]
This tool cannot handle pointcloud data beyond 2-3 million points.

**Comment by madhavkarri** [comment]
It would not even load data for pointcloud data that contained roughly 16 million points

**Comment by hop-soellingeraj** [comment]
Do you know what it would take to make it do larger point clouds, assuming my GPU is large enough?  I have a pretty large GPU on this workstation, and meshlab loads this file no problem.  It takes about 800MB of gpu memory.

**Comment by hop-soellingeraj** [comment]
What I noticed was that there is no indication that the tool is using my GPU.  This GPU is a QuadroM4000, and it's the only one installed.  So it's not like the tool is loading onto another GPU.  I noticed inside the docker-compose there is no reservation for the gpu, which is typical of other gpu enabled containers I use.  I didn't know if the GPU support is supposed to be embedded in one of the dependencies and thus not visible in the repo.

**Comment by madhavkarri** [comment]
I do not think it has to do with hardware limitations. Inherently it has to do with Hitachi tool limitations, rather than hardware.

**Comment by INF800** [comment]
> What I noticed was that there is no indication that the tool is using my GPU. This GPU is a QuadroM4000, and it's the only one installed. So it's not like the tool is loading onto another GPU. I noticed inside the docker-compose there is no reservation for the gpu, which is typical of other gpu enabled containers I use. I didn't know if the GPU support is supposed to be embedded in one of the dependencies and thus not visible in the repo.

I opened new issue for the discussion

**Comment by INF800** [comment]
@madhavkarri @hop-soellingeraj @dmandrioli . What was the conclusion of this issue.

**Comment by dmandrioli** [comment]
@INF800 The tool relies on Three.js for point cloud display. Maybe some improvements are possible for this tool but the main limitation is Three.js.
