### ISSUE TITLE
Question about changing the name of classes

### ISSUE THREAD

**Issue by MartinMao1101** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#148]
Hi Dmandrioli, hi everyone
since i found that the setting of classes and corresponding names are defined in settings.json, i just would like to ask if it is possible to change the names directly in this file?
If not possible, how should i change them?
Thank you very much for your help!

**Comment by dmandrioli** [comment]
Hi, yes you can define your own set of classes by editing settings.json
Look at the README for more informations.
