### ISSUE TITLE
How to add a ability to Pan View

### ISSUE THREAD

**Issue by FroFan** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#150]
Hello, we find this project very helpful to us!
However, we cannot move the center of the point clouds when we want to edit. We want to ask that how could we add a ability to Pan View for this editor? Could you give us some suggestions?
Thank you very much!

**Comment by dmandrioli** [comment]
Hi, thanks for your comment.
You can change the center of the point cloud view by clicking a point with the middle button of the mouse.
Source: [README](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#using-the-point-cloud-editor)

**Comment by FroFan** [comment]
@dmandrioli Oh, we didn't notice that. Thank you very much!
