### ISSUE TITLE
How can I import data

### ISSUE THREAD

**Issue by truongthihuonggiang** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#151]
I have big project, and each person in my team work for set of image, how can I import the to one for checking. THanks alot.

**Comment by CecilHarvey** [comment]
cannot quite understand what you mean

but for bigger projects it might be better to develop your own backend which uses the editor code of semantic-segmentation-editor as frontend, with whatever features you would like to use, like accounts, workflows, etc.

**Comment by truongthihuonggiang** [comment]
Thank you for your idea. I have read and add some functions like import json file to add to mongodb.
