### ISSUE TITLE
how can i read label & object file with python?

### ISSUE THREAD

**Issue by Willforcv** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#152]
how can i read label & object file with python?

thanks~

**Comment by gzchenjiajun** [comment]
Have you solved this problem? I also need to parse the label file

**Comment by VLDMR-BS** [comment]
Hi
Where I can find a documentation about read label file in python?

**Comment by MoritzLennartz** [comment]
Is there a solution this problem? i am also struggeling with this
