### ISSUE TITLE
Sorry, this project uses Meteor 1.12, which is not installed and could not be downloaded.

### ISSUE THREAD

**Issue by fengzi2016** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#154]
when I run meteor npm start, I met the question
![image](https://user-images.githubusercontent.com/22490787/132657062-7dd4dd84-18f0-41c3-987c-e0706ffc8aab.png)
it is always 0%
how to solve it?
3q

**Comment by CecilHarvey** [comment]
use a VPN, you know what I mean

**Comment by fengzi2016** [comment]
Thanks for your answer, I used it, but it didn't work.
To solve this problem, modify the hosts file











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor] Sorry, this project uses Meteor 1.12, which is not installed and could not be downloaded. (#154)





 
use a VPN, you know what I mean
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fengzi2016** [comment]
Is there a way to get the project running without meteor?
My purpose is to learn some implementation logic of point cloud segmentation.

Thanks
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor] Sorry, this project uses Meteor 1.12, which is not installed and could not be downloaded. (#154)





 
use a VPN, you know what I mean
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmandrioli** [comment]
No, it's not possible to run the tool without Meteor.
