### ISSUE TITLE
Is it able for us to make changes to the editor by ourselves

### ISSUE THREAD

**Issue by jjjmmmxxx** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#156]
Hello. Thanks a lot for the semantic segmentation editor! It helps us a lot. 
We now hope to add a little function for the editor, such as add point clouds of a 3D box to the point clouds for our use. Is it possible that we can add this kind of function, or the core of the editor is integrated and could not be changed? The code seems very unfamiliar with us and we would like to spend time on that.

**Comment by howz-chen** [comment]
First of all, thanks to this great job. 
I need function which output 3D bbox info about labeled point cloud too, but I am not familiar with JavaScript, so is there any intention to add this or any suggestion about how to change it? 
@dmandrioli  Looking forward to your reply.
