### ISSUE TITLE
Where the labeled data is storaged?

### ISSUE THREAD

**Issue by foreverbest** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#159]
Hi, thanks for this great project.
Currently I face an issue that prevent me from access the mongo db and thus I cannot activate the entirely app. I want to backup my labeled images thus I could **edit** it after reinstall the whole project. Could you please provide some advise for this? Thanks very much.

**Comment by dmandrioli** [comment]
Bitmap labeling is stored in the Mongo database, you might want to use `mongodump` to backup your database.
