### ISSUE TITLE
Black screen on MacOs

### ISSUE THREAD

**Issue by Fraer** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#16]
Hello, i have a black screen when running the app even if the input folder contains .jpg images.
Permissions on the input folder are set to drwxrwxrwx

No error in logs.

macOs 10.13.6
METEOR@1.7.0.5

**Comment by dmandrioli** [comment]
Duplicates #14

**Comment by dmandrioli** [comment]
Feel free to elaborate in #14 if you have any information that could help to understand the issue. The app is running as expected on my OSX 10.12
