### ISSUE TITLE
What is the difference between label and object?

### ISSUE THREAD

**Issue by SijanNeupane49** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#167]
![Screenshot from 2022-02-16 13-02-13](https://user-images.githubusercontent.com/77236738/154260890-f184c8dd-01d6-4ae8-92e2-6e88cb520053.png)
I see under object column -1 what does this -1 refers to ? What is the relation/difference between label and object notation? I once got values for both label and object as 2 and for label 0 and 1 object as -1. I know the label is counted for void as 0 and there under it increases but how it is done for object. I could not understand this. Please I request you for help. Thank you in advance.

**Comment by dmandrioli** [comment]
A point in the point cloud can have just a class (label) or a class and an object instance (object). Imagine you have several cars parked along a road, you want to be able to distinguish the different cars. 
-1 means "no label/object"
