### ISSUE TITLE
Loading millions of data points 

### ISSUE THREAD

**Issue by INF800** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#169]
Currently, the webapp has a serious limitation because three.js loads entire point cloud at once. Because of this reason, we cannot load large datasets. Can we take some ideas from potree and make tweaks to this app so that annotations on large datasets is possible?

**Comment by INF800** [comment]
Reference to potree https://github.com/potree/potree

**Comment by INF800** [comment]
Pptk https://developer.here.com/blog/interactive-visualization-of-10m-3d-points-with-new-open-source-python-package-pptk from python can do it only for 100M points. But potree can load more.

**Comment by dmandrioli** [comment]
Duplicates #145
