### ISSUE TITLE
unable to install meteor

### ISSUE THREAD

**Issue by eiffelbastin** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#170]
hi,
I was trying to install Semantic Segmentation Editor, as mentioned in the installation guide in GitHub. But when I try to install 'Meteor' I am getting this error from my terminal.
![image](https://user-images.githubusercontent.com/83037376/156333196-360fc422-d3bc-483d-9526-061531738b47.png)
 can someone suggest what to do...

**Comment by dmandrioli** [comment]
As a matter of fact your platform does not support Meteor...
This is not the right place to complain :)
