### ISSUE TITLE
Export segmentations as separate image

### ISSUE THREAD

**Issue by dpattison3** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#18]
I might have missed it, but is there a way to export just the segmentations as images? Downloading the image saves the image with both the original and overlaid segmentations. I'm aware of the JSON format, but is there an easy tool for translating that into a segmentation image?

**Comment by dmandrioli** [comment]
Before clicking the download button, you can push the opacity of annotations to 100% with the slider "Objects Opacity".
