### ISSUE TITLE
cannot find  XXX.pcd.objects and XXX.pcd.labels when loading .pcd files.

### ISSUE THREAD

**Issue by migowei0621** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#21]
The error is :
Error: ENOENT: no such file or directory, stat '/home/wenjingw/pcd_annotation/semantic-segmentation-editor/output/1532169145283189.pcd.objects'

and I cant load pcd file.

**Comment by migowei0621** [comment]
Oh, does it only support ascii format? my pcd file is in binary format.

**Comment by dmandrioli** [comment]
Yes (#1)

**Comment by migowei0621** [comment]
Sorry. I'm also confused that the output label format is original point and  its label / object  attributes, right?
and why did the coordinates of the points after labelling change?

**Comment by dmandrioli** [comment]
Points coordinates are not supposed to change. If you want you can you attach your failing PCD file to this thread to see what's happening.
