### ISSUE TITLE
What is the specific data stored in the xxx.pcd.labels and xxx.pcd.objects？

### ISSUE THREAD

**Issue by WangWangPoint** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#22]
what is the result of the 3D point cloud editor? How could I know the size of 3D bounding box? is that in the xxx.pcd.labels?

**Comment by dmandrioli** [comment]
>what is the result of the 3D point cloud editor?

You get the result of the 3D segmentation using the [API](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#api-endpoints)

>How could I know the size of 3D bounding box?

This tool does not provide this feature.

>is that in the xxx.pcd.labels?

xxx.pcd.labels is an internal representation of the segmentation. Only use the API to retrieve the result.
