### ISSUE TITLE
Is OUTPUT_FOLDER error?

### ISSUE THREAD

**Issue by yunfeihaha** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#23]
OUTPUT_FOLDER is no files after labeled

**Comment by dmandrioli** [comment]
OUTPUT_FOLDER is only for 3D labeling. Do you label 3D point clouds ?

**Comment by yunfeihaha** [comment]
No. I need to label 2d image. but I can't find the results while an image had been labeled.

**Comment by dmandrioli** [comment]
You can get the result using [API Endpoints](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#api-endpoints).

**Comment by yunfeihaha** [comment]
thank you very much, I try it
