### ISSUE TITLE
The navigator should not retrieve annotation data but only file names

### ISSUE THREAD

**Issue by brucechou1983** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#24]
Hi, thanks for sharing this great tool. Currently the only way to navigate to next/previous image is going back to the browsing mode and select the image. I think it's fine because it only costs a small fraction of time comparing to finish a segmentation label. However, I found it become much slower when I have more than a thousand labels in the MongoDB. Then I checked the requests:

![image](https://user-images.githubusercontent.com/8468820/47688570-01fa1c00-dc21-11e8-8998-751b1f5de256.png)

and also the preview of the response
![image](https://user-images.githubusercontent.com/8468820/47688657-52717980-dc21-11e8-8ec0-52076e746163.png)

It downloads every single record in the system every time when going back to the file browsing mode. So the whole system will become slower and slower over the time. I'm trying to figure out how to fix this issue, but I'm not familiar with some part of the tech stack used in this project. Would be grateful if someone could help.

** I use the suggested docker image `jshimko/meteor-launchpad:latest` and chrome browser

**Comment by dmandrioli** [comment]
Hey, thank you for your feedback. I don't reproduce, can you take a screenshot of some expanded items of this 5MB array? Also note that the docker image is not up to date and there is no plan to update it so you may want to use the current git version.

**Comment by brucechou1983** [comment]
@dmandrioli thanks for the support. These items are "ALL" labels store is my collection.
![image](https://user-images.githubusercontent.com/8468820/47768111-89bf5380-dd11-11e8-89e6-d938ac6b3d6f.png)

I use `jshimko/meteor-launchpad:latest` (a one line dockerfile) to launch this app with current git version.

**Comment by dmandrioli** [comment]
This is a weakness of the app that need some work. Thanks for reporting.

**Comment by brucechou1983** [comment]
@dmandrioli Thanks for confirming the issue. Is there anything I can help?

**Comment by dmandrioli** [comment]
Sure, pull requests are welcome :)

**Comment by brucechou1983** [comment]
Since I don't use the all annotated feature, I simply forced the annotated variables to empty lists.

**Comment by dmandrioli** [comment]
Great! It looks good, I will review and apply your merge request it in the next couple of days. 
Thank you for your contribution.

**Comment by brucechou1983** [comment]
You're welcome. Thanks for sharing this great tool.

**Comment by dmandrioli** [comment]
Merged! Thanks Bruce.
