### ISSUE TITLE
Should only load information about one image when entering editor mode

### ISSUE THREAD

**Issue by brucechou1983** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#26]
Hi, I faced another performance issue. When label number approaching ten thousand I found the speed of entering editing mode becomes much slower again. Then I check the network and see this response.

![image](https://user-images.githubusercontent.com/8468820/48454298-aff4f100-e7f1-11e8-9278-258533e66ecd.png)

I grep the keyword "removed" and found nothing meaningful. Could you give me a hint about how to fix this? Thanks.

**Comment by brucechou1983** [comment]
No. I'm using this commit.

> 44979b38

I've check the changlog of v1.1.2. Seems like there are only some Meteor dependency changes. I would like to know where these responses come from so I could debug and fix thems.

**Comment by dmandrioli** [comment]
As a matter of fact, these logs are [DDP](https://github.com/meteor/meteor/blob/master/packages/ddp/DDP.md) messages but I don't know why you are seeing them. And I don't have time to label 10000 images so it will be difficult to reproduce :)
Look. in the direction of subscriptions and publications like you did before.

**Comment by brucechou1983** [comment]
@dmandrioli Thanks. I will look into DDP. BTW, I don't manually create 10000 labels, I use a model to 
label these images so I only have to fix some of them.

**Comment by dmandrioli** [comment]
Fixed in 44979b38ce119ab6a75cf18b6df412da4eae1988
