### ISSUE TITLE
Next img is displayed as null.

### ISSUE THREAD

**Issue by sankim90** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#28]
1. I work 174 images & click next button

![1](https://user-images.githubusercontent.com/36911945/48522755-3b878400-e8bd-11e8-8f22-71c737de5690.png)

2. Next img is displayed as null.
![2](https://user-images.githubusercontent.com/36911945/48522819-6a055f00-e8bd-11e8-97ab-95c1d84819e8.png)

3. http://localhost:3000/browse/1/20/null -> http://localhost:3000/browse/1/20

![3](https://user-images.githubusercontent.com/36911945/48522930-bcdf1680-e8bd-11e8-98f2-e3c647b8da98.png)

worked.

It is bug?

**Comment by dmandrioli** [comment]
@sankim90 Thanks for reporting.

**Comment by dhirajsuvarna** [comment]
This issue doesn't seems to be solved. I am still getting this error.
