### ISSUE TITLE
How can I get the data stored in .labels ?

### ISSUE THREAD

**Issue by JoeyCrane** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#33]
I tried to read the data as:

> labels= [int(line) for line in f]
and the feedback was:

> File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 4: invalid start byte

So how can I get the data?

**Comment by dmandrioli** [comment]
Hi, .labels and .objects files are internal representation of the 3D segmentation, they are not readable as-is. You can get your data using the [API](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#api-endpoints)
