### ISSUE TITLE
Editor windows do not open

### ISSUE THREAD

**Issue by thirdlastletter** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#36]
When I try to run the app with "meteor npm start" I get the following:

`Number of available sets of object classes: 3
=> Started your app.

=> App running at: http://localhost:3000/
`

but I can`t see any of the editor windows. 

Does anyone know how to fix this?

I`m using semantic-segmentation-editor-1.1.2 on Ubuntu 16.04.

**Comment by dmandrioli** [comment]
Hi, did you open http://localhost:3000/ with your favorite browser (chrome or firefox)?

**Comment by thirdlastletter** [comment]
Thank you! That was my mistake!
