### ISSUE TITLE
how to use the pcd output data?

### ISSUE THREAD

**Issue by luckyluckydadada** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#39]
In the output_dir, generate xxxx.pcd.labels and xxxx,pcd.objects , how to use the output data?

**Comment by luckyluckydadada** [comment]
What format is the output file and what tool is used for reading？

**Comment by dmandrioli** [comment]
These files are internal storage for the tool, you can't read them.
To retrieve your PCD labelling, use the [API](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#api-endpoints.)
