### ISSUE TITLE
TypeError: Cannot destructure property `imagesFolder` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by imistyrain** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#4]
After spenting 2 hours of install meteor and depencies, I succeed to build it. But when try to run, I got this error.
Is there any suggestion?
W20180730-18:21:40.261(8)? (STDERR) Error while parsing config.json
W20180730-18:21:40.348(8)? (STDERR) C:\Users\****\AppData\Local\.meteor\packages\meteor-tool\1.6.1_3\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20180730-18:21:40.350(8)? (STDERR)                                             throw(ex);
W20180730-18:21:40.350(8)? (STDERR)                                             ^
W20180730-18:21:40.351(8)? (STDERR)
W20180730-18:21:40.352(8)? (STDERR) TypeError: Cannot destructure property `imagesFolder` of 'undefined' or 'null'.
W20180730-18:21:40.352(8)? (STDERR)     at api.js (server/api.js:13:61)
W20180730-18:21:40.353(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180730-18:21:40.353(8)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180730-18:21:40.354(8)? (STDERR)     at D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\app\app.js:1015:1
W20180730-18:21:40.354(8)? (STDERR)     at D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\boot.js:411:36
W20180730-18:21:40.357(8)? (STDERR)     at Array.forEach (<anonymous>)
W20180730-18:21:40.358(8)? (STDERR)     at D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\boot.js:220:19
W20180730-18:21:40.359(8)? (STDERR)     at D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\boot.js:471:5
W20180730-18:21:40.368(8)? (STDERR)     at Function.run (D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\profile.js:510:12)
W20180730-18:21:40.372(8)? (STDERR)     at D:\Detection\AnnotationTools\semantic-segmentation-editor\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
W20180730-18:21:46.480(8)? (STDERR) Error while parsing config.json

**Comment by dmandrioli** [comment]
As a matter of fact there is a probleum with your config.json. Can you copy/paste its content here?

**Comment by imistyrain** [comment]
{
  "configuration": {
    "input-folder": "images", // The root folder containing images and PCD files
    "output-folder": "outputs" // Segmentation data (only 3D) will be stored in this folder
  },
  // The different sets of classes available in the tool
  // For object classes, only the 'label' field is mandatory
  // The icon field can be set with an icon from the mdi-material-ui package
  "sets-of-classes": [
    {
      "name": "Cityscapes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Road", "color": "#804080", "icon": "Road"},
      {"label": "Sidewalk", "color": "#F423E8", "icon": "NaturePeople"},
      {"label": "Parking", "color": "#FAAAA0", "icon": "Parking"},
      {"label": "Rail Track", "color": "#E6968C", "icon": "Train"},
      {"label": "Person", "color": "#DC143C", "icon": "Walk"},
      {"label": "Rider", "color": "#FF0000", "icon": "Motorbike"},
      {"label": "Car", "color": "#0000E8", "icon": "Car"},
      {"label": "Truck", "color": "#000046", "icon": "Truck"},
      {"label": "Bus", "color": "#003C64", "icon": "Bus"},
      {"label": "On Rails", "color": "#E6968C", "icon": "Train"},
      {"label": "Motorcycle", "color": "#0000E6", "icon": "Motorbike"},
      {"label": "Bicycle", "color": "#770B20", "icon": "Bike"},
      {"label": "Caravan", "color": "#00005A", "icon": "Caravan"},
      {"label": "Trailer", "color": "#00006E", "icon": "TruckTrailer"},
      {"label": "Building", "color": "#464646", "icon": "HomeVariant"},
      {"label": "Wall", "color": "#66669C", "icon": "Wall"},
      {"label": "Fence", "color": "#BE9999", "icon": "Gate"},
      {"label": "Guard Rail", "color": "#B4A5B4", "icon": "SignCaution"},
      {"label": "Bridge", "color": "#966464", "icon": "Bridge"},
      {"label": "Tunnel", "color": "#96785A", "icon": "AlarmLight"},
      {"label": "Pole", "color": "#999999", "icon": "Instapaper"},
      {"label": "Pole Group", "color": "#999999", "icon": "Instapaper"},
      {"label": "Traffic Sign", "color": "#DCDC00", "icon": "SignDirection"},
      {"label": "Traffic Light", "color": "#FAAA1E", "icon": "TrafficLight"},
      {"label": "Vegetation", "color": "#6B8E23", "icon": "PineTree"},
      {"label": "Terrain", "color": "#98FB98", "icon": "Terrain"},
      {"label": "Sky", "color": "#4682B4", "icon": "WeatherPartlycloudy"},
      {"label": "Ground", "color": "#510051", "icon": "Drag"},
      {"label": "Dynamic", "color": "#6F4A00", "icon": "RunFast"},
      {"label": "Static", "color": "#000000", "icon": "Anchor"}
    ]
    },
    {
      "name": "AD20",
      "objects": [
        {"label": "VOID", "color": "#CFCFCF"},
        {
          "label": "Void",
          "color": "#FF8800",
          "icon": "BorderNoneVariant"
        }, {
          "label": "Road",
          "color": "#799024",
          "icon": "Road"
        },
        {
          "label": "Pedestrian",
          "color": "#FAFFF5",
          "icon": "Walk"
        },
        {
          "label": "Car",
          "color": "#FF6D67",
          "icon": "Car"
        },
        {
          "label": "Truck",
          "color": "#FF5B8E",
          "icon": "Truck"
        },
        {
          "label": "Bus",
          "color": "#FF6FA2",
          "icon": "Bus"
        },
        {
          "label": "On rails",
          "color": "#FF7FC3",
          "icon": "Train"
        },
        {
          "label": "Motorcycle",
          "color": "#FFA859",
          "icon": "Motorbike"
        },
        {
          "label": "Bicycle",
          "color": "#FFDB62",
          "icon": "Bike"
        },
        {
          "label": "Sky",
          "color": "#87D8FF",
          "icon": "WeatherPartlycloudy"
        },
        {
          "label": "Vegetation",
          "color": "#7BC32B",
          "icon": "PineTree"
        },
        {
          "label": "Sidewalk",
          "color": "#827E67",
          "icon": "NaturePeople"
        },
        {
          "label": "Traffic sign",
          "color": "#9E9BFF",
          "icon": "SignDirection"
        },
        {
          "label": "Lane marking",
          "color": "#DDCDFF",
          "icon": "RoadVariant"
        },
        {
          "label": "Building",
          "color": "#785C6F",
          "icon": "HomeVariant"
        },
        {
          "label": "Traffic light",
          "color": "#119599",
          "icon": "SignDirection"
        },
        {
          "label": "Snow covered",
          "color": "#F1F1EF",
          "icon": "Snowflake"
        },
        {
          "label": "Pole",
          "color": "#FBB577",
          "icon": "Instapaper"
        },
        {
          "label": "Unpaved road",
          "color": "#C0AE89",
          "icon": "BlurLinear"
        },
        {
          "label": "Guard rail",
          "color": "#4D3D48",
          "icon": "SignCaution"
        }
      ]
    },
    {
      "name": "33 Classes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Class 1"},
      {"label": "Class 2"},
      {"label": "Class 3"},
      {"label": "Class 4"},
      {"label": "Class 5"},
      {"label": "Class 6"},
      {"label": "Class 7"},
      {"label": "Class 8"},
      {"label": "Class 9"},
      {"label": "Class 10"},
      {"label": "Class 11"},
      {"label": "Class 12"},
      {"label": "Class 13"},
      {"label": "Class 14"},
      {"label": "Class 15"},
      {"label": "Class 16"},
      {"label": "Class 17"},
      {"label": "Class 18"},
      {"label": "Class 19"},
      {"label": "Class 20"},
      {"label": "Class 21"},
      {"label": "Class 22"},
      {"label": "Class 23"},
      {"label": "Class 24"},
      {"label": "Class 25"},
      {"label": "Class 26"},
      {"label": "Class 27"},
      {"label": "Class 28"},
      {"label": "Class 29"},
      {"label": "Class 30"},
      {"label": "Class 31"},
      {"label": "Class 32"}
    ]
    }
  ]
}

**Comment by AXING620** [comment]
i also encountered this problem,my config.json is like follow:
{
  "configuration": {
    "input-folder": "G:/tiaoyan_image_all/segment_train_0724", // The root folder containing images and PCD files
    "output-folder": "G:/tiaoyan_image_all/segment_train_0724" // Segmentation data (only 3D) will be stored in this folder
  },
  // The different sets of classes available in the tool
  // For object classes, only the 'label' field is mandatory
  // The icon field can be set with an icon from the mdi-material-ui package
  "sets-of-classes": [
    {
      "name": "Cityscapes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Road", "color": "#804080", "icon": "Road"},
      {"label": "Sidewalk", "color": "#F423E8", "icon": "NaturePeople"},
      {"label": "Parking", "color": "#FAAAA0", "icon": "Parking"},
      {"label": "Rail Track", "color": "#E6968C", "icon": "Train"},
      {"label": "Person", "color": "#DC143C", "icon": "Walk"},
      {"label": "Rider", "color": "#FF0000", "icon": "Motorbike"},
      {"label": "Car", "color": "#0000E8", "icon": "Car"},
      {"label": "Truck", "color": "#000046", "icon": "Truck"},
      {"label": "Bus", "color": "#003C64", "icon": "Bus"},
      {"label": "On Rails", "color": "#E6968C", "icon": "Train"},
      {"label": "Motorcycle", "color": "#0000E6", "icon": "Motorbike"},
      {"label": "Bicycle", "color": "#770B20", "icon": "Bike"},
      {"label": "Caravan", "color": "#00005A", "icon": "Caravan"},
      {"label": "Trailer", "color": "#00006E", "icon": "TruckTrailer"},
      {"label": "Building", "color": "#464646", "icon": "HomeVariant"},
      {"label": "Wall", "color": "#66669C", "icon": "Wall"},
      {"label": "Fence", "color": "#BE9999", "icon": "Gate"},
      {"label": "Guard Rail", "color": "#B4A5B4", "icon": "SignCaution"},
      {"label": "Bridge", "color": "#966464", "icon": "Bridge"},
      {"label": "Tunnel", "color": "#96785A", "icon": "AlarmLight"},
      {"label": "Pole", "color": "#999999", "icon": "Instapaper"},
      {"label": "Pole Group", "color": "#999999", "icon": "Instapaper"},
      {"label": "Traffic Sign", "color": "#DCDC00", "icon": "SignDirection"},
      {"label": "Traffic Light", "color": "#FAAA1E", "icon": "TrafficLight"},
      {"label": "Vegetation", "color": "#6B8E23", "icon": "PineTree"},
      {"label": "Terrain", "color": "#98FB98", "icon": "Terrain"},
      {"label": "Sky", "color": "#4682B4", "icon": "WeatherPartlycloudy"},
      {"label": "Ground", "color": "#510051", "icon": "Drag"},
      {"label": "Dynamic", "color": "#6F4A00", "icon": "RunFast"},
      {"label": "Static", "color": "#000000", "icon": "Anchor"}
    ]
    },
    {
      "name": "AD20",
      "objects": [
        {"label": "VOID", "color": "#CFCFCF"},
        {
          "label": "Void",
          "color": "#FF8800",
          "icon": "BorderNoneVariant"
        }, {
          "label": "Road",
          "color": "#799024",
          "icon": "Road"
        },
        {
          "label": "Pedestrian",
          "color": "#FAFFF5",
          "icon": "Walk"
        },
        {
          "label": "Car",
          "color": "#FF6D67",
          "icon": "Car"
        },
        {
          "label": "Truck",
          "color": "#FF5B8E",
          "icon": "Truck"
        },
        {
          "label": "Bus",
          "color": "#FF6FA2",
          "icon": "Bus"
        },
        {
          "label": "On rails",
          "color": "#FF7FC3",
          "icon": "Train"
        },
        {
          "label": "Motorcycle",
          "color": "#FFA859",
          "icon": "Motorbike"
        },
        {
          "label": "Bicycle",
          "color": "#FFDB62",
          "icon": "Bike"
        },
        {
          "label": "Sky",
          "color": "#87D8FF",
          "icon": "WeatherPartlycloudy"
        },
        {
          "label": "Vegetation",
          "color": "#7BC32B",
          "icon": "PineTree"
        },
        {
          "label": "Sidewalk",
          "color": "#827E67",
          "icon": "NaturePeople"
        },
        {
          "label": "Traffic sign",
          "color": "#9E9BFF",
          "icon": "SignDirection"
        },
        {
          "label": "Lane marking",
          "color": "#DDCDFF",
          "icon": "RoadVariant"
        },
        {
          "label": "Building",
          "color": "#785C6F",
          "icon": "HomeVariant"
        },
        {
          "label": "Traffic light",
          "color": "#119599",
          "icon": "SignDirection"
        },
        {
          "label": "Snow covered",
          "color": "#F1F1EF",
          "icon": "Snowflake"
        },
        {
          "label": "Pole",
          "color": "#FBB577",
          "icon": "Instapaper"
        },
        {
          "label": "Unpaved road",
          "color": "#C0AE89",
          "icon": "BlurLinear"
        },
        {
          "label": "Guard rail",
          "color": "#4D3D48",
          "icon": "SignCaution"
        }
      ]
    },
    {
      "name": "33 Classes", "objects": [
      {"label": "VOID", "color": "#CFCFCF"},
      {"label": "Class 1"},
      {"label": "Class 2"},
      {"label": "Class 3"},
      {"label": "Class 4"},
      {"label": "Class 5"},
      {"label": "Class 6"},
      {"label": "Class 7"},
      {"label": "Class 8"},
      {"label": "Class 9"},
      {"label": "Class 10"},
      {"label": "Class 11"},
      {"label": "Class 12"},
      {"label": "Class 13"},
      {"label": "Class 14"},
      {"label": "Class 15"},
      {"label": "Class 16"},
      {"label": "Class 17"},
      {"label": "Class 18"},
      {"label": "Class 19"},
      {"label": "Class 20"},
      {"label": "Class 21"},
      {"label": "Class 22"},
      {"label": "Class 23"},
      {"label": "Class 24"},
      {"label": "Class 25"},
      {"label": "Class 26"},
      {"label": "Class 27"},
      {"label": "Class 28"},
      {"label": "Class 29"},
      {"label": "Class 30"},
      {"label": "Class 31"},
      {"label": "Class 32"}
    ]
    }
  ]
}

**Comment by austingg** [comment]
it works when I installed ss-editor on CentOS. Something wrong with Windows path?

**Comment by dmandrioli** [comment]
The app now works on windows. Thanks all for reporting this issue.
