### ISSUE TITLE
How to link My Images added in "semantic-segmentation-editor-1.1.2\private\samples""  its not working

### ISSUE THREAD

**Issue by RajasekharKadasani** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#40]

**Comment by RajasekharKadasani** [comment]
how can i load image form server

**Comment by dmandrioli** [comment]
Hi, I don't get your question, please elaborate.

**Comment by RajasekharKadasani** [comment]
sorry,
I did setup App and trying to use ,How can i use my images either from local/server to load in this application instead of default images

**Comment by dmandrioli** [comment]
Edit settings.json. By default, images are served from HOME/sse-images, not private/samples
https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#configuration-file-settingsjson

**Comment by RajasekharKadasani** [comment]
actually i am new to this Meteor app,
i followed steps and did setup but after build i didnt have any folder "sse-images"

**Comment by dmandrioli** [comment]
What do you see on the console when you start the app?

**Comment by RajasekharKadasani** [comment]
thank you i got that folder now

**Comment by Sajjadmanal** [comment]
@RajasekharKadasani Where did you find it? I am unable to find.
