### ISSUE TITLE
"Esc" and "Enter" do not work when using Polygon Drawing Tool.

### ISSUE THREAD

**Issue by youngxiao** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#41]
When drawing polygon on my images, "Enter" button does not work and "Esc" key does not work too.

**Comment by dmandrioli** [comment]
I have not been able to reproduce on the demo? Do you?
http://sse.hup.li/edit/%2Fsamples%2Fbitmap.png
