### ISSUE TITLE
rectangle--rectangle shape is disturbing while editing

### ISSUE THREAD

**Issue by RajasekharKadasani** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#42]
i tried drawing Rectangle ,then i tried selecting drawn rectangle its selecting but if i trying edit/drag only one corner is dragging

**Comment by dmandrioli** [comment]
I have not been able to reproduce on the demo? Do you?
http://sse.hup.li/edit/%2Fsamples%2Fbitmap.png

**Comment by RajasekharKadasani** [comment]
![Uploading 1.PNG…]()
![Uploading 2.PNG…]()

**Comment by RajasekharKadasani** [comment]
i can reproduce i am not able to post picture here
