### ISSUE TITLE
Unable to run the tool for pointcloud

### ISSUE THREAD

**Issue by Sajjadmanal** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#43]
I have successfully installed Meteor using Chocolatey but I am unable to run the tool. Could you please suggest how to proceed further using this tool?
I am using Windows OS.

**Comment by dmandrioli** [comment]
Hi, what do you see on the console when you run the tool?

**Comment by Sajjadmanal** [comment]
Hi @dmandrioli I was encountering with errors while is run the command: `meteor npm start`
Now, it's working fine. Thanks..!!
