### ISSUE TITLE
How to use .pcd file produced by aerial photogrammetry?

### ISSUE THREAD

**Issue by Do-Hwan** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#48]
Hi, I use your editor for labeling pcd point cloud data.
I made point cloud data file using drone and pix4d program. 
There are x,y,z and r,g,b and scalar information in my point cloud data.
what data is in your sample(pointcloud_labeling.pcd)?

**Comment by dmandrioli** [comment]
Hi, the sample pcd file contains only XYZ coordinates, you can open it, it's a text file.
Thanks for your interest in the project.

**Comment by dmandrioli** [comment]
Reference: #47
