### ISSUE TITLE
how to input my point could data

### ISSUE THREAD

**Issue by ChenXie93** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#49]
@dmandrioli i know how to use tha eiitor follow the readme.txt, but i'm confused how to imput my data, i didn't find any information about how to input my own point cloud data. wolud you please tell me how to solve the problem.
Thanks, looking forward your reply!

**Comment by dmandrioli** [comment]
Hi, the default folder for input (bitmap and point cloud) is by default HOMEDIR/sse-images.  It can be changed in settings.json
You just have to copy your .pcd files to this folder.
