### ISSUE TITLE
MDI default export is not declared in imported module

### ISSUE THREAD

**Issue by ruanhailiang** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#55]
import MDI, {ChevronRight, Eye, EyeOff} from 'mdi-material-ui';
MDI default export is not declared in imported module  why  ?

**Comment by dmandrioli** [comment]
Hi, could you elaborate? I don't understand your question. Thanks.

**Comment by ruanhailiang** [comment]
![error](https://user-images.githubusercontent.com/15086045/64156700-e0347b80-ce67-11e9-84b2-e99ad9077ea2.png)

**Comment by ruanhailiang** [comment]
![error](https://user-images.githubusercontent.com/15086045/64156838-18d45500-ce68-11e9-95d0-fefda77a5633.png)

**Comment by dmandrioli** [comment]
Thanks, this is just a warning of your IDE, you may want to ask the author of this package but it's fully harmless.
