### ISSUE TITLE
3D and 2D annotation on point cloud 

### ISSUE THREAD

**Issue by abhigoku10** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#56]
@dmandrioli @brucechou1983 @etlapale  thanks for the wonderful code base amazing work i have few queries

1. Can we perform 3D bounding box on point cloud and 2D annotation on th image instead of polygon
2. what is the liciense of this tool

**Comment by dmandrioli** [comment]
Hi @abhigoku10, thanks for your kind words.
1. No
2. MIT Licence
