### ISSUE TITLE
Incorrect number of points in exported PCD file.

### ISSUE THREAD

**Issue by anderiri2** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#58]
In the 3D editor, when the downloading the annotated PCD, the number of points indicated in the metadata of the file indicates that there are three times as much as the real number of points.

**Comment by anderiri2** [comment]
@twbabyduck thak you for the answer. Yes I think that at the moment I need to program an script to change the metadata.

**Comment by dmandrioli** [comment]
@anderiri2 Thanks for reporting
