### ISSUE TITLE
2 bugs about polygon drawing tool in bitmap image editor.

### ISSUE THREAD

**Issue by haiwangbee** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#61]
Hi:
  This is an awesome tool, great job!
  I found 2 bugs in bitmap image editor with polygon drawing tool:
  1. I can't use ESC to remove last created points in reverse order.
  2.If I haven't close the polygon and use ctrl+Z to undo, I will not use polygon drawing tool anymore.

**Comment by dmandrioli** [comment]
I'll fix these bugs, thanks for reporting.
