### ISSUE TITLE
can not delete marked points in pcd-editor

### ISSUE THREAD

**Issue by Darknesszlx** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#62]
![image](https://user-images.githubusercontent.com/7909474/69403671-22b67780-0d36-11ea-85a1-f301ba85a4be.png)
Hi, dmandrioli!
It's really an amazing tool!
after selecting some points using "+", I need to remove some points from previous selected point sets, but "-" seems doesn't work! waiting for your help! Thank you!

**Comment by dmandrioli** [comment]
Hi, thanks for your kind words. The behaviour of "-" is not perfect but you have to draw a shape around the point(s) to remove them from selection.
