### ISSUE TITLE
Several questions...

### ISSUE THREAD

**Issue by aviadper** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#63]
Hi :-)

1. I'm using a docker. where can I see the configuration json file?
2. Is that possible to annotate the lidar points while seeing the image?
3. I cannot save the labeling output file. It says that the image is corrupted.

Thank you!

**Comment by dmandrioli** [comment]
Hi, alignment between bitmap and lidar data is not implemented, no way to annotate them together.
The provided docker image is based on v1.0 which is outdated.
Investigating your docker issues would need to have a new image based on the last version of the tool.

Thanks

**Comment by aviadper** [comment]
Thank you. I used this image:
docker pull hitachiail/semantic-segmentation-editor

Where can I find the new version?

**Comment by dmandrioli** [comment]
As of today there is no up-to-date docker image embedding the last version of the tool (1.1.4)

**Comment by aviadper** [comment]
Thank you.
Does the new version have alignment between bitmap and lidar data

**Comment by dmandrioli** [comment]
It would be a nice feature, but alignment is not implemented.
