### ISSUE TITLE
Show RGB info in point cloud

### ISSUE THREAD

**Issue by Darknesszlx** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#65]
![image](https://user-images.githubusercontent.com/7909474/69866062-ff636d80-12dd-11ea-8640-964ff145aa41.png)
![image](https://user-images.githubusercontent.com/7909474/69866076-0ab69900-12de-11ea-8e29-86237b3aeded.png)
Hi, dmandrioli!
I modify some code in SsePCDLoader.js file, as the debug log shows, r g b value have been pushed in color, but output does not show any color info as the attached pics show;
Waiting for your kind replay, Thank you!

**Comment by dmandrioli** [comment]
Hi, displaying colored pointclouds is not currently supported, the color array is only used to display selected points in red.
