### ISSUE TITLE
How to parse label and object?

### ISSUE THREAD

**Issue by Darknesszlx** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#68]
/api/pcdtext/[PATH_TO_FILE]: (3D only) Get the labeling of a pcd file using 2 addditional columns: label and object

How to parse these 2 addditional columns: label and object?

**Comment by dmandrioli** [comment]
Are you talking about loading a pre-labeled PCD file in the tool?

**Comment by Darknesszlx** [comment]
No, after labeling a pcd file, it will generate pcd_file_name.pcd.labels and pcd_file_name.pcd.objects, I think these two files saved marked info, but I don't know how to parse them in python or other programming language. Did I misunderstand these two files?
![image](https://user-images.githubusercontent.com/7909474/70511742-9ba53400-1b6a-11ea-8dbd-c166f8b39021.png)

**Comment by dmandrioli** [comment]
pcd_file_name.pcd.labels and pcd_file_name.pcd.objects are binary compressed internal files, they are not supposed to be used. When you call the API you get a consolidated text PCD file with two additional columns.

**Comment by Darknesszlx** [comment]
OK, thanks for your replay!
