### ISSUE TITLE
How do I reference this work

### ISSUE THREAD

**Issue by GuoliangShi** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#73]
Hi, if i used this tool to annotate my datas. Which paper should I cite, or just cite this website?

**Comment by dmandrioli** [comment]
Hi, you can just cite this website. 
Thanks.

**Comment by dmandrioli** [comment]
@GuoliangShi Just curious, where did you reference the project? :) 
Thanks

**Comment by GuoliangShi** [comment]
Thank you for your very effective work. My paper hasn't been submitted yet. I believe with Point Cloud Neural Network research goes deeper. Your work can help more researchers.

**Comment by dmandrioli** [comment]
Thanks for your kindness. Let me know when submitted and you can also cite my name, Damien Mandrioli, if you want.
Best
