### ISSUE TITLE
Performance very laggy when using large pointcloud.

### ISSUE THREAD

**Issue by CecilHarvey** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#74]
I'm using pointcloud file generated with Velodyne VLS-128 (which contains 180669 points) and the performance is very laggy.

Reason might be the projection of ALL points are updated whenever user makes any move (rotating, panning, etc.)

I commented out updatePixelProjection(idx) and it no longer lags (this does make the labeling tool unusable though).

It would be much better if this could be optimized.

**Comment by dmandrioli** [comment]
Just pushed a new version which improve a lot performance of pointcloud labeling. Can you give it a try?

**Comment by CecilHarvey** [comment]
the latest version improves performance a lot. Thanks :)
