### ISSUE TITLE
Unable to read the pcd data.

### ISSUE THREAD

**Issue by TianchaoHuo** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#80]
Firstly thanks for sharing a nice tool. while using this editor for my own pcd file,  I can not get any points on the screen. But I can see the point cloud in the pcl_viewer tools instead. 
![2020-03-23 16-21-12](https://user-images.githubusercontent.com/37928758/77298171-76a58d00-6d25-11ea-96f1-8c1de573fe49.png)

As you can see, the points can be detected by the editor however it can not be shown on the screen.
![2020-03-23 16-24-39屏幕截图](https://user-images.githubusercontent.com/37928758/77298183-7ad1aa80-6d25-11ea-81bf-28411b7cbea1.png)

I assume that the problem is from the data type : ascii or binary. Do I need to slightly modify or configure  the editor files? 

Could you help me to solve this problem ? Looking forward to your reply, thanks in advance.

**Comment by dmandrioli** [comment]
Hi, yes you may have to change your input file, supported fields are described [here](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#pcd-support).
Can you share the PCD file that fails to display?

**Comment by TianchaoHuo** [comment]
> Hi, yes you may have to change your input file, supported fields are described [here](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#pcd-support).
> Can you share the PCD file that fails to display?

Thanks for your quick reply！ the PCD file can be download here:
https://drive.google.com/open?id=1qGiIK6G_jQ1GvOs8B2Qhn4JQVJdl32Uq

I think I this PCD file has binary format.

**Comment by CecilHarvey** [comment]
Your PCD file has NaN points, which is currently not supported.
Could you try removing all NaN points from your PCD file?

> Thanks for your quick reply！ the PCD file can be download here:
> https://drive.google.com/open?id=1qGiIK6G_jQ1GvOs8B2Qhn4JQVJdl32Uq
> 
> I think I this PCD file has binary format.

**Comment by TianchaoHuo** [comment]
> Your PCD file has NaN points, which is currently not supported.
> Could you try removing all NaN points from your PCD file?
> 
> > Thanks for your quick reply！ the PCD file can be download here:
> > https://drive.google.com/open?id=1qGiIK6G_jQ1GvOs8B2Qhn4JQVJdl32Uq
> > I think I this PCD file has binary format.
