### ISSUE TITLE
Can I add other objects to label from outside of the objects list?

### ISSUE THREAD

**Issue by xamxixixo** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#85]
Hello,

By "objects list" I refer to the list in which these buttons are: Void, Road, Sidewalk, Parking, Rail Track, Person, Car and so on to the end of that column.

Is it possible to add other objects, for example a Microphone, or a Hard Drive, or anything? This program seems to be specifically for labeling those which are on the road for autonomous driving.

**Comment by dmandrioli** [comment]
Hi, icons in settings.json are picked from https://github.com/mui-org/material-ui/releases/tag/v1.1.0 they are not mandatory (you can leave the field empty) and you can use any icons from this library which is not limited to roads etc. Mor generally, the tool is not dedicated to autonomous driving, you can edit the ontology in settings.json.

**Comment by xamxixixo** [comment]
thank you
