### ISSUE TITLE
how to convert .obj to .pcd file

### ISSUE THREAD

**Issue by jay-thakur** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#89]
Hi,

I have installed this tool & its working fine for me. 

I have .obj files & i need to convert it to .pcd. 

Could you please guide me if there is any tool / code to convert .obj to .pcd.

Thanks,
Jay

**Comment by dmandrioli** [comment]
Hi Jay, I have no recommendation to convert OBJ to PCD, you should find some projects doing that on Github. Just curious, what is the origin of your OBJ point clouds?

**Comment by jay-thakur** [comment]
@dmandrioli  Thanks. ohk. i have downloaded shapenet dataset.
