### ISSUE TITLE
Special characters in filenames are not correctly handled

### ISSUE THREAD

**Issue by lionel88cn** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#9]
The edit functions works fine but json api failed

**Comment by dmandrioli** [comment]
Could you provide the following information to reproduce your issue:
 - operating system running the server
 - browser or tool (curl, etc...) and operating system consuming the JSON API
 - exact failing file name

Thanks

**Comment by dmandrioli** [comment]
Thanks, the problem can be generalized to special chars in filenames, especially spaces.
