### ISSUE TITLE
Mouse right button in pointcloud doesn't work.

### ISSUE THREAD

**Issue by wuyushuwys** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#91]
Mouse right button functionality in pointcloud doesn't work, can anyone help me with that?

**Comment by dmandrioli** [comment]
So you can't select points using mouse right button drag&drop? Does something happen when you do this?

**Comment by wuyushuwys** [comment]
No, I can't select points using mouse right button. When I dragged my mouse with pressing right mouse button, it would act like the reset the view. I built it from source in Ubuntu and ran in Chrome.

**Comment by dmandrioli** [comment]
Does it work with http://sse.hup.li/edit/%2Fpointcloud_labeling.pcd ?

**Comment by wuyushuwys** [comment]
Just test it on OSX. It works on OSX&safari but chrome still doesn't work. It seems that is related to the browser.

**Comment by dmandrioli** [comment]
It works on OSX/Chrome on my side so I guess it's about Ubuntu/Chrome. I will investigate, thanks.

**Comment by wuyushuwys** [comment]
I just found there may be some conficts with chrome extensions. after i deactivated all chrome extension it works well. Thanks!
