### ISSUE TITLE
How to move view point?

### ISSUE THREAD

**Issue by aidonchuk** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#94]
Hi! Could you tell me is possible to move view point to another location? Please
Some times difficult to make annotation only from center position.

**Comment by dmandrioli** [comment]
Hi! You can mouse middle click a point to change the center of orbital
navigator

**Comment by aidonchuk** [comment]
Wow! That's so cool magic! Thanks you very much)
