### ISSUE TITLE
Demo on the main page for the bitmap editor doesn't work

### ISSUE THREAD

**Issue by urishab** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#97]
Giving me the following error:

Your app is crashing. Here's the latest log:
Semantic Segmentation Editor
Images (JPG, PNG, PCD) served from /home/ssedemo/sse-images
PCD binary segmentation data stored in /home/ssedemo/sse-internal
Number of available sets of object classes: 3
=> Meteor server restarted
meteor://ðŸ’»app/app/app.js:438
  if (bytes.byteLength > 0) {
            ^

TypeError: Cannot read property 'byteLength' of undefined
    at bytesToObject (server/SseDataWorkerServer.js:198:15)
    at Object.uncompress (server/SseDataWorkerServer.js:207:26)
    at ReadFileContext.readFile (server/api.js:88:48)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
Exited with code: 1
Your application is crashing. Waiting for file change.
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.

**Comment by urishab** [comment]
direct link to the demo:
http://sse.hup.li/edit/%2Fbitmap_labeling.png

**Comment by dmandrioli** [comment]
Thanks for reporting, it works now.

**Comment by urishab** [comment]
THanks! That's service :)
