### ISSUE TITLE
PCD labels not getting removed

### ISSUE THREAD

**Issue by DarioSiroki** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#98]
Steps to reproduce:

1. you have a fresh pcd
![image](https://user-images.githubusercontent.com/30674077/86472811-0ead0c80-bd40-11ea-90a3-e4a1ba282ee3.png)

2. mark the whole area as one label (or you can just label a part of it, doesn't matter)

![image](https://user-images.githubusercontent.com/30674077/86472856-21274600-bd40-11ea-8c07-986d29c5ee19.png)

3. refresh the page, everything's cool

![image](https://user-images.githubusercontent.com/30674077/86472923-3bf9ba80-bd40-11ea-8a3d-2b6bb0da384e.png)

4. now delete object "5"
5. refresh page, all of the points are still labeled green:

![image](https://user-images.githubusercontent.com/30674077/86472966-516ee480-bd40-11ea-8a4a-c4f1ecf1a41a.png)

sorry for cropped screenshots

**Comment by dmandrioli** [comment]
Thanks for reporting

**Comment by coolsnake** [comment]
thanks
