### ISSUE TITLE
Questions about pcd point cloud loading

### ISSUE THREAD

**Issue by baifanxxx** [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor#99]
Hello author, 
Thank you very much for designing this tool, it greatly helped our work. However, I encountered the problem of loading point cloud files. I successfully configured this tool on the Windows 10 system, but when I load the point cloud file in pcd format in the webpage, the webpage has been waiting and cannot be loaded successfully. When I try to load a jpg format image, the loading speed is very fast and I can edit it directly. I don't understand what caused this. My computer is equipped with 1050TI GPU and 4G memory. The point cloud file loaded is only Stanford's rabbit, not big. Hope you can help me solve this problem, thank you very much!

**Comment by dmandrioli** [comment]
Hi, to investigate what's going on, can you share "Stanford's rabbit" you are talking about?

**Comment by baifanxxx** [comment]
Hi,
Thanks for your help. I have solved this problem.&nbsp;Different browsers will affect the display of point cloud.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 凌晨4:56
收件人:&nbsp;"Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor"<semantic-segmentation-editor@noreply.github.com&gt;;
抄送:&nbsp;"BAI Fan"<826989019@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor] Questions about pcd point cloud loading (#99)





 
Hi, to investigate what's going on, can you share "Stanford's rabbit" you are talking about?
